[package]
name = "pod-operation"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.7"
tokio = { version = "1.41.1", features = ["full"] }
socketioxide = "0.15.1"
rppal = { version = "0.18.0", features = ["hal"]}
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
i2cdev = "0.3.1"
vl53l0x = "1.0.1"